### ISSUE TITLE
Better Approach to producer consumer Problem

### ISSUE THREAD

**Issue by sam09** [lakshmanaram/Operating-Systems-Problems#10]
A better solution would be to have separate processes as producer and consumer and have a shared buffer and semaphore.That is the correct way considering it is a multi-process synchronization problem.

[Wiki](https://en.wikipedia.org/wiki/Producer%E2%80%93consumer_problem)

**Comment by lakshmanaram** [comment]
implementing semaphore within the same program was easier. So started off with that, sure will change it. Thanks.

**Comment by lakshmanaram** [comment]
[https://github.com/lakshmanaram/Operating-Systems-Problems/commit/e82cb9236df1cacb9b2ea8ebf68b48f767194427](url) commit makes the required changes. Thanks for pointing it out! :smiley:
