### ISSUE TITLE
"Simple Page Replacement" algorithm incorrect

### ISSUE THREAD

**Issue by prajwalkr** [lakshmanaram/Operating-Systems-Problems#6]
![screenshot from 2016-04-11 08 51 47](https://cloud.githubusercontent.com/assets/8796788/14415913/d09e086c-ffc1-11e5-9766-4ba4ebf7fd41.png)

FIFO was incorrect, I added the right code. I haven't seen the other two properly.

**Comment by lakshmanaram** [comment]
I'll clean the code and check the remaining.
